name: GitHub Actions
run-name: ${{ github.actor }} is pushing
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: e2e testing
        run: npm run test:e2e
      - name: test migration
        run: npm run migrate:test
      - name: lint checking
        run: npm run lint
      - name: finish
        run: echo "Actions were proceeded successfully 🚀"
